//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.19 at 09:47:46 PM EDT 
//


package com.mss.cus.xml.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccountInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="ServiceNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ConsumptionInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Consumption" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ChargeDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="BilledConsumption" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="DaysOfService" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="BilledCharge" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="Counter" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accountInfo",
    "consumptionInfo"
})
@XmlRootElement(name = "ConsumptionHistory")
public class ConsumptionHistory {

    @XmlElement(name = "AccountInfo", required = true)
    protected ConsumptionHistory.AccountInfo accountInfo;
    @XmlElement(name = "ConsumptionInfo", required = true)
    protected ConsumptionHistory.ConsumptionInfo consumptionInfo;

    /**
     * Gets the value of the accountInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ConsumptionHistory.AccountInfo }
     *     
     */
    public ConsumptionHistory.AccountInfo getAccountInfo() {
        return accountInfo;
    }

    /**
     * Sets the value of the accountInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsumptionHistory.AccountInfo }
     *     
     */
    public void setAccountInfo(ConsumptionHistory.AccountInfo value) {
        this.accountInfo = value;
    }

    /**
     * Gets the value of the consumptionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ConsumptionHistory.ConsumptionInfo }
     *     
     */
    public ConsumptionHistory.ConsumptionInfo getConsumptionInfo() {
        return consumptionInfo;
    }

    /**
     * Sets the value of the consumptionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsumptionHistory.ConsumptionInfo }
     *     
     */
    public void setConsumptionInfo(ConsumptionHistory.ConsumptionInfo value) {
        this.consumptionInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="ServiceNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accountNumber",
        "serviceNumber"
    })
    public static class AccountInfo {

        @XmlElement(name = "AccountNumber")
        protected int accountNumber;
        @XmlElement(name = "ServiceNumber")
        protected int serviceNumber;

        /**
         * Gets the value of the accountNumber property.
         * 
         */
        public int getAccountNumber() {
            return accountNumber;
        }

        /**
         * Sets the value of the accountNumber property.
         * 
         */
        public void setAccountNumber(int value) {
            this.accountNumber = value;
        }

        /**
         * Gets the value of the serviceNumber property.
         * 
         */
        public int getServiceNumber() {
            return serviceNumber;
        }

        /**
         * Sets the value of the serviceNumber property.
         * 
         */
        public void setServiceNumber(int value) {
            this.serviceNumber = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Consumption" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ChargeDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="BilledConsumption" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="DaysOfService" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="BilledCharge" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="Counter" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "consumption"
    })
    public static class ConsumptionInfo {

        @XmlElement(name = "Consumption", required = true)
        protected List<ConsumptionHistory.ConsumptionInfo.Consumption> consumption;

        /**
         * Gets the value of the consumption property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the consumption property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConsumption().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ConsumptionHistory.ConsumptionInfo.Consumption }
         * 
         * 
         */
        public List<ConsumptionHistory.ConsumptionInfo.Consumption> getConsumption() {
            if (consumption == null) {
                consumption = new ArrayList<ConsumptionHistory.ConsumptionInfo.Consumption>();
            }
            return this.consumption;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ChargeDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="BilledConsumption" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="DaysOfService" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="BilledCharge" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="Counter" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "chargeDate",
            "billedConsumption",
            "daysOfService",
            "billedCharge",
            "counter"
        })
        public static class Consumption {

            @XmlElement(name = "ChargeDate", required = true)
            protected String chargeDate;
            @XmlElement(name = "BilledConsumption")
            protected double billedConsumption;
            @XmlElement(name = "DaysOfService")
            protected int daysOfService;
            @XmlElement(name = "BilledCharge")
            protected double billedCharge;
            @XmlElement(name = "Counter")
            protected int counter;

            /**
             * Gets the value of the chargeDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChargeDate() {
                return chargeDate;
            }

            /**
             * Sets the value of the chargeDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChargeDate(String value) {
                this.chargeDate = value;
            }

            /**
             * Gets the value of the billedConsumption property.
             * 
             */
            public double getBilledConsumption() {
                return billedConsumption;
            }

            /**
             * Sets the value of the billedConsumption property.
             * 
             */
            public void setBilledConsumption(double value) {
                this.billedConsumption = value;
            }

            /**
             * Gets the value of the daysOfService property.
             * 
             */
            public int getDaysOfService() {
                return daysOfService;
            }

            /**
             * Sets the value of the daysOfService property.
             * 
             */
            public void setDaysOfService(int value) {
                this.daysOfService = value;
            }

            /**
             * Gets the value of the billedCharge property.
             * 
             */
            public double getBilledCharge() {
                return billedCharge;
            }

            /**
             * Sets the value of the billedCharge property.
             * 
             */
            public void setBilledCharge(double value) {
                this.billedCharge = value;
            }

            /**
             * Gets the value of the counter property.
             * 
             */
            public int getCounter() {
                return counter;
            }

            /**
             * Sets the value of the counter property.
             * 
             */
            public void setCounter(int value) {
                this.counter = value;
            }

        }

    }

}
