//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.21 at 02:23:14 PM EDT 
//


package com.mss.cus.xml.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mss.cus.xml.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mss.cus.xml.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PaymentHistory }
     * 
     */
    public PaymentHistory createPaymentHistory() {
        return new PaymentHistory();
    }

    /**
     * Create an instance of {@link PaymentHistory.PaymentInfo }
     * 
     */
    public PaymentHistory.PaymentInfo createPaymentHistoryPaymentInfo() {
        return new PaymentHistory.PaymentInfo();
    }

    /**
     * Create an instance of {@link PaymentHistory.AccountInfo }
     * 
     */
    public PaymentHistory.AccountInfo createPaymentHistoryAccountInfo() {
        return new PaymentHistory.AccountInfo();
    }

    /**
     * Create an instance of {@link PaymentHistory.PaymentInfo.Payments }
     * 
     */
    public PaymentHistory.PaymentInfo.Payments createPaymentHistoryPaymentInfoPayments() {
        return new PaymentHistory.PaymentInfo.Payments();
    }

}
